import type { CSSProperties } from "react";

// Shared design tokens
export const colors = {
  bg: "#0a0a0a",
  bgCard: "#141414",
  bgCardAlt: "#0d0d0d",
  bgRow: "#1e293b",
  bgRowAlt: "#162032",
  border: "#2a2a2a",
  borderSubtle: "#1f1f1f",
  text: "#e5e5e5",
  textMuted: "#94a3b8",
  textFaint: "#64748b",
  textDim: "#666",
  accent: "#f97316",
  accentBg: "#1f1200",
  blue: "#6366f1",
  green: "#10b981",
  red: "#ef4444",
  amber: "#f59e0b",
  purple: "#a855f7",
  indigo: "#818cf8",
  cyan: "#22d3ee",
  white: "#f1f5f9",
} as const;

// Reusable style objects — mirrors the `S` constant in App.js
export const S: Record<string, CSSProperties> = {
  loading: {
    textAlign: "center",
    padding: 64,
    color: "#666",
    fontSize: 16,
    fontFamily: "monospace",
  },
  card: {
    background: "#141414",
    borderRadius: 4,
    padding: 24,
    border: "1px solid #2a2a2a",
  },
  cardTitle: {
    margin: "0 0 16px",
    fontFamily: "monospace",
    fontSize: 13,
    fontWeight: 700,
    color: "#f97316",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  badge: {
    background: "#1f1f1f",
    color: "#888",
    fontSize: 11,
    padding: "3px 10px",
    borderRadius: 2,
    fontFamily: "monospace",
  },
  tab: {
    background: "none",
    border: "none",
    padding: "10px 18px",
    color: "#666",
    cursor: "pointer",
    borderBottom: "2px solid transparent",
    borderRadius: "6px 6px 0 0",
    transition: "all 0.15s",
    fontSize: 12,
    fontFamily: "monospace",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  tabActive: {
    color: "#f97316",
    borderBottom: "2px solid #f97316",
    fontWeight: 700,
    background: "linear-gradient(180deg, rgba(249,115,22,0.04), rgba(249,115,22,0.13))",
  },
  navBtn: {
    background: "none",
    border: "none",
    padding: "6px 14px",
    color: "#999",
    cursor: "pointer",
    borderRadius: 2,
    fontSize: 12,
    fontFamily: "monospace",
  },
  navBtnActive: { color: "#f97316", background: "#1f1200", fontWeight: 700 },
  backBtn: {
    background: "none",
    border: "none",
    color: "#f97316",
    cursor: "pointer",
    padding: "0 0 16px",
    display: "block",
    fontSize: 13,
    fontFamily: "monospace",
  },
  searchInput: {
    width: 260,
    padding: "8px 14px",
    borderRadius: 2,
    border: "1px solid #2a2a2a",
    fontSize: 13,
    outline: "none",
    background: "#0a0a0a",
    color: "#e5e5e5",
    fontFamily: "monospace",
  },
  dropdown: {
    position: "absolute",
    right: 0,
    top: "100%",
    width: 420,
    background: "#141414",
    border: "1px solid #2a2a2a",
    borderRadius: 4,
    boxShadow: "0 8px 24px rgba(0,0,0,0.8)",
    zIndex: 200,
    maxHeight: 320,
    overflowY: "auto",
  },
  dropdownItem: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 16px",
    cursor: "pointer",
    borderBottom: "1px solid #1f1f1f",
  },
  select: {
    padding: "8px 12px",
    borderRadius: 2,
    border: "1px solid #2a2a2a",
    fontSize: 12,
    background: "#141414",
    color: "#ccc",
    cursor: "pointer",
    outline: "none",
    fontFamily: "monospace",
  },
  // Accent overrides spread onto a filter control when it has a value set, so
  // active filters stand out from empty ones (matches the Advanced button).
  // Uses the `border` shorthand (not borderColor) to match S.select — mixing
  // shorthand/non-shorthand triggers a React warning when the style toggles off.
  selectActive: {
    border: "1px solid #f97316",
    color: "#fb923c",
    background: "#1f1200",
  },
  table: {
    width: "100%",
    borderCollapse: "separate" as const,
    borderSpacing: 0,
    fontSize: 12,
    fontFamily: "monospace",
  },
  th: {
    textAlign: "left" as const,
    padding: "8px 12px",
    background: "#0a0a0a",
    color: "#f97316",
    fontSize: 10,
    fontWeight: 700,
    borderBottom: "1px solid #2a2a2a",
    whiteSpace: "nowrap" as const,
    textTransform: "uppercase" as const,
    letterSpacing: 0.5,
    position: "sticky" as const,
    top: 0,
    zIndex: 1,
  },
  td: {
    padding: "9px 12px",
    borderBottom: "1px solid #1a1a1a",
    color: "#ccc",
    whiteSpace: "nowrap" as const,
  },
  tdNum: {
    padding: "9px 12px",
    borderBottom: "1px solid #1a1a1a",
    textAlign: "right" as const,
    fontFamily: "monospace",
    fontSize: 12,
    whiteSpace: "nowrap" as const,
    color: "#e5e5e5",
  },
  tooltip: {
    background: "#141414",
    border: "1px solid #2a2a2a",
    borderRadius: 4,
    fontSize: 12,
    color: "#e5e5e5",
    fontFamily: "monospace",
  },
};
